/**
 * Данные заполнители.
 *
 * @author Markitanov Vadim
 * @since 08.01.2025
 */
import { Tag } from '@/app/lib/model/entity/Tag'
import { WordEntity } from '@/app/lib/model/word'

/**
 * TODO:
 * Муха
 * Оранжевый
 */

const TAGS: Tag[] = [
  { id: 1, name: 'Разное' },
  { id: 2, name: 'Числительные', color: '#808080' },
  { id: 3, name: 'Цвета', color: '#F59E0B' },
  { id: 4, name: 'Фрукты', color: '#4CAF50' },
  { id: 5, name: 'Овощи', color: '#EF4444' },
  { id: 6, name: 'Дом', color: '#D8B384' },
  { id: 7, name: 'Животные', color: '#FB923C' },
  { id: 8, name: 'Строения', color: '#6B7280' },
  { id: 9, name: 'Природа', color: '#1E3A8A' },
  { id: 10, name: 'Еда и напитки', color: '#9A3412' },
  { id: 11, name: 'Человеческое тело', color: '#F5D7B6' },
  { id: 12, name: 'Материал', color: '#2C3E50' },
  { id: 13, name: 'Птицы', color: '#87CEEB' },
  { id: 14, name: 'Город и село', color: '#8B4513' },
  { id: 15, name: 'Профессии', color: '#FFD700' },
  { id: 16, name: 'Одежда', color: '#FFC0CB' },
  { id: 17, name: 'Прилагательные', color: '#8A2BE2' },
  { id: 18, name: 'Глаголы', color: '#FF5733' },
  { id: 19, name: 'Цветы', color: '#FFB6C1' },
  { id: 20, name: 'Насекомые', color: '#FFD700' }
]

const createWord = (ru: string, kg: string, tag: number, en?: string): WordEntity => {
  return { id: 0, ru: ru, kg: kg, tag: tag, en: en }
}

const WORDS: WordEntity[] = [
  // Разное
  createWord('Работа', 'Иш, жумуш', 1, 'Job'),
  createWord('Игра', 'Оюн', 1, 'Game'),
  createWord('Начальник, сумка', 'Баштык', 1, 'Boss, bag'),
  createWord('Слово', 'Сөз', 1, 'Word'),
  createWord('Словарь', 'Сөздүк', 1, 'Dictionary'),
  createWord('Книга', 'Китеп', 1, 'Book'),
  createWord('Ребёнок', 'Бала', 1, 'Child'),
  createWord('Песня', 'Ыр', 1, 'Song'),
  createWord('Равно', 'Барабар', 1, 'Equals'),
  createWord('Больше', 'Чоң', 1, 'More'),
  createWord('Плюс', 'Кошуу белгиси', 1, 'Plus'),
  createWord('Умножение', 'Көбөйтүү', 1, 'Multiplication'),
  createWord('Деление', 'Бөлүү', 1, 'Division'),
  createWord('Знак, метка', 'Белги', 1, 'Sing, mark'),
  createWord('Деньги', 'Акча', 1, 'Money'),
  createWord('Лопата', 'Күрөк', 1, 'Shovel'),
  createWord('Хорошо', 'Жакшы', 1, 'Fine'),
  createWord('Плохо', 'Жаман', 1, 'Badly'),
  createWord('Полёт', 'Учуу', 1, 'Flight'),
  // Числительные
  createWord('Ноль', 'Нөл', 2, 'Zero'),
  createWord('Один', 'Бир', 2, 'One'),
  createWord('Два', 'Эки', 2, 'Two'),
  createWord('Три', 'Үч', 2, 'Three'),
  createWord('Четыре', 'Төрт', 2, 'Four'),
  createWord('Пять', 'Беш', 2, 'Five'),
  createWord('Шесть', 'Алты', 2, 'Six'),
  createWord('Семь', 'Жети', 2, 'Seven'),
  createWord('Восемь', 'Сегиз', 2, 'Eight'),
  createWord('Девять', 'Тогуз', 2, 'Nine'),
  createWord('Десять', 'Он', 2, 'Ten'),
  createWord('Двадцать', 'Жыйырма', 2, 'Twenty'),
  createWord('Тридцать', 'Отуз', 2, 'Thirty'),
  createWord('Сорок', 'Кырк', 2, 'Forty'),
  createWord('Пятьдесят', 'Элүү', 2, 'Fifty'),
  createWord('Шестьдесят', 'Алтымыш', 2, 'Sixty'),
  createWord('Семьдесят', 'Жетимиш', 2, 'Seventy'),
  createWord('Восемьдесят', 'Сексен', 2, 'Eighty'),
  createWord('Девяносто', 'Токсон', 2, 'Ninety'),
  createWord('Тысяча', 'Миң', 2, 'Thousand'),
  // Цвета
  createWord('Белый', 'Ак', 3, 'White'),
  createWord('Черный', 'Кара', 3, 'Black'),
  createWord('Красный', 'Кызыл', 3, 'Red'),
  createWord('Зеленый', 'Жашыл', 3, 'Green'),
  createWord('Синий', 'Көк', 3, 'Blue'),
  createWord('Желтый', 'Сары', 3, 'Yellow'),
  createWord('Оранжевый', 'Кызгыл сары|Ачык күрөң', 3, 'Orange'),
  createWord('Фиолетовый', 'Кызгылт көк', 3, 'Purple'),
  createWord('Розовый', 'Кызыл, кызгылт', 3, 'Pink'),
  createWord('Коричневый', 'Күрөң', 3, 'Brown'),
  createWord('Серый', 'Боз, сур, көк', 3, 'Gray'),
  createWord('Голубой', 'Көк ачык', 3, 'Light Blue'),
  createWord('Бирюзовый', 'Бирюза түстүү', 3, 'Turquoise'),
  createWord('Лиловый', 'Кызгылт көгүш', 3, 'Lilac'),
  createWord('Песочный', 'Кум түстүү', 3, 'Sand'),
  createWord('Коралловый', 'Шуру (маржан) түстүү', 3, 'Coral'),
  createWord('Золотой', 'Алтын', 3, 'Gold'),
  createWord('Серебряный', 'Күмүш', 3, 'Silver'),
  createWord('Бронзовый', 'Коло түстүү', 3, 'Bronze'),
  // Фрукты
  createWord('Яблоко', 'Алма', 4, 'Apple'),
  createWord('Груша', 'Алмурут', 4, 'Pear'),
  createWord('Виноград', 'Жүзүм', 4, 'Grape'),
  createWord('Арбуз', 'Дарбыз', 4, 'Water melon'),
  createWord('Дыня', 'Коон', 4, 'Melon'),
  createWord('Гранат', 'Анар', 4, 'Pomegranate'),
  createWord('Абрикос', 'Өрүк', 4, 'Apricot'),
  createWord('Персик', 'Шабдалы', 4, 'Peach'),
  createWord('Хурма', 'Курма', 4, 'Persimmon'),
  // Овощи
  createWord('Картофель', 'Картөшкө', 5, 'Potato'),
  createWord('Морковь', 'Сабиз', 5, 'Carrot'),
  createWord('Лук', 'Пияз', 5, 'Onion'),
  createWord('Чеснок', 'Сарымсак', 5, 'Garlic'),
  createWord('Горох', 'Буурчак', 5, 'Peas'),
  createWord('Огурец', 'Бадыраң', 5, 'Cucumber'),
  createWord('Капуста', 'Капуста', 5, 'Cabbage'),
  // Дом
  createWord('Дом', 'Үй', 6, 'House'),
  createWord('Этаж', 'Кабат', 6, 'Floor'),
  createWord('Дверь', 'Эшик', 6, 'Door'),
  createWord('Окно', 'Терезе', 6, 'Window'),
  createWord('Ложка', 'Кашык', 6, 'Spoon'),
  createWord('Нож', 'Бычак', 6, 'Knife'),
  createWord('Ключ', 'Ачкыч', 6, 'Key'),
  createWord('Подушка', 'Жаздык', 6, 'Pillow'),
  createWord('Мыло', 'Самын', 6, 'Soap'),
  // Животные
  createWord('Кошка', 'Мышык', 7, 'Cat'),
  createWord('Собака', 'Ит', 7, 'Dog'),
  createWord('Корова', 'Уй', 7, 'Cow'),
  createWord('Медведь', 'Аюу', 7, 'Bear'),
  createWord('Осёл', 'Эшек', 7, 'Donkey'),
  createWord('Олень', 'Бугу', 7, 'Deer'),
  createWord('Лось', 'Багыш', 7, 'Elk'),
  createWord('Свинья', 'Чочко', 7, 'Pig'),
  createWord('Поросёнок', 'Торпой', 7, 'Piglet'),
  createWord('Слон', 'Пил', 7, 'Elephant'),
  createWord('Лев', 'Арстан', 7, 'Lion'),
  createWord('Тигр', 'Жолборс', 7, 'Tiger'),
  createWord('Верблюд', 'Төө', 7, 'Camel'),
  createWord('Лягушка', 'Бака', 7, 'Frog'),
  createWord('Бык', 'Бука', 7, 'Bull'),
  createWord('Черепаха', 'Ташбака', 7, 'Turtle'),
  createWord('Заяц', 'Коён', 7, 'Hare'),
  createWord('Кролик', 'Кролик', 7, 'Rabbit'),
  createWord('Лошадь', 'Жалкы', 7, 'Horse'),
  createWord('Жеребёнок', 'Кулун', 7, 'Foal'),
  // Строения
  createWord('Магазин', 'Дүкөн', 8, 'Shop'),
  createWord('Аптека', 'Дарыкана', 8, 'Pharmacy'),
  createWord('Школа', 'Мектеп', 8, 'School'),
  createWord('Больница', 'Оорукана', 8, 'Hospital'),
  createWord('Гостиница', 'Мейманкана', 8, 'Hotel'),
  createWord('Библиотека', 'Китепкана', 8, 'Library'),
  createWord('Парикмахерская', 'Чачтарач', 8, 'Salon'),
  createWord('Типография', 'Басманкана', 8, 'Printing house'),
  createWord('Стоматология', 'Тишкана', 8, 'Dentistry'),
  // Природа
  createWord('Море', 'Деңиз', 9, 'Sea'),
  createWord('Гора', 'Тоо', 9, 'Mountain'),
  createWord('Лес', 'Токой', 9, 'Forest'),
  createWord('Озеро', 'Көл', 9, 'Lake'),
  createWord('Дерево', 'Жыгач', 9, 'Tree'),
  createWord('Камень', 'Таш', 9, 'Stone'),
  createWord('Снег', 'Кар', 9, 'Snow'),
  createWord('Поле', 'Талла', 9, 'Field'),
  createWord('Пруд', 'Көлмө', 9, 'Pond'),
  createWord('Река', 'Дарыя', 9, 'River'),
  createWord('Зима', 'Кыш', 9, 'Winter'),
  createWord('Весна', 'Жаз', 9, 'Spring'),
  createWord('Лето', 'Жай', 9, 'Summer'),
  createWord('Осень', 'Күз', 9, 'Autumn'),
  // Еда и напитки
  createWord('Еда', 'Тамак', 10, 'Food'),
  createWord('Вода', 'Суу', 10, 'Water'),
  createWord('Молоко', 'Сүт', 10, 'Milk'),
  createWord('Пиво', 'Сыра', 10, 'Beer'),
  createWord('Водка', 'Арак', 10, 'Vodka'),
  createWord('Мясо', 'Эт', 10, 'Meat'),
  createWord('Хлеб', 'Нан', 10, 'Bread'),
  createWord('Соль', 'Туз', 10, 'Salt'),
  createWord('Кукуруза', 'Жүгөрү', 10, 'Corn'),
  createWord('Гриб', 'Козу карын', 10, 'Mushroom'),
  createWord('Яд', 'Уу', 10, 'Poison'),
  createWord('Мёд', 'Бал', 10, 'Honey'),
  // Человеческое тело
  createWord('Человек', 'Адам', 11, 'Human'),
  createWord('Голова', 'Баш', 11, 'Head'),
  createWord('Глаз', 'Көз', 11, 'Eye'),
  createWord('Нос', 'Мурун', 11, 'Nose'),
  createWord('Палец', 'Бармак', 11, 'Finger'),
  createWord('Рука', 'Кол', 11, 'Hand'),
  createWord('Волос', 'Чач', 11, 'Hair'),
  createWord('Кровь', 'Кан', 11, 'Blood'),
  createWord('Зуб', 'Тиш', 11, 'Tooth'),
  createWord('Нога', 'Бут', 11, 'Leg'),
  createWord('Внутренность', 'Ич', 11, 'Interior'),
  createWord('Борода', 'Сакал', 11, 'Beard'),
  // Материал
  createWord('Золото', 'Алтын', 12, 'Gold'),
  createWord('Серебро', 'Күмүш', 12, 'Silver'),
  createWord('Уголь', 'Көмүр', 12, 'Coal'),
  createWord('Железо', 'Темир', 12, 'Iron'),
  createWord('Песок', 'Кум', 12, 'Sand'),
  createWord('Древесина', 'Жыгач', 12, 'Wood'),
  createWord('Бумага', 'Кагаз', 12, 'Paper'),
  // Птицы
  createWord('Птица', 'Куш', 13, 'Bird'),
  createWord('Курица', 'Тоок', 13, 'Hen'),
  createWord('Петух', 'Короз', 13, 'Cock'),
  createWord('Голубь', 'Көгүчкөн', 13, 'Pigeon'),
  createWord('Ворона', 'Карга', 13, 'Crow'),
  createWord('Орёл', 'Бүркүт', 13, 'Eagle'),
  createWord('Сова', 'Үкү', 13, 'Owl'),
  createWord('Фазан', 'Кыргоол', 13, 'Peacock'),
  createWord('Куропатка', 'Чил', 13, 'Partridge'),
  createWord('Синица', 'Синица', 13, 'Blue-tit'),
  createWord('Индюк', 'Күрп, үндүк', 13, 'Turkey'),
  createWord('Снегирь', 'Снегирь', 13, 'Bullfinch'),
  // Город и село
  createWord('Город', 'Шаар', 14, 'City'),
  createWord('Село, деревня', 'Айыл', 14, 'Village'),
  createWord('Улица', 'Көчө', 14, 'Street'),
  createWord('Площадь', 'Аянт', 14, 'Square'),
  createWord('Мост', 'Көпүрө', 14, 'Bridge'),
  createWord('Торговый центр', 'Соода борбору', 14, 'Shopping mall'),
  createWord('Дорога', 'Жол', 14, 'Road'),
  createWord('Уличный фонарь', 'Панар', 14, 'Street lamp'),
  createWord('Мечеть', 'Мечит', 14, 'Mosque'),
  createWord('Рынок', 'Базар', 14, 'Market'),
  createWord('Ж/д вокзал', 'Темир жол вокзалы', 14, 'Railway station'),
  // Профессии
  createWord('Мастер', 'Уста', 15, 'Master'),
  createWord('Строитель', 'Куруучу', 15, 'Builder'),
  createWord('Учитель', 'Мугалим', 15, 'Teacher'),
  createWord('Преподаватель', 'Окутуучу', 15, 'Teacher'),
  createWord('Рыбак', 'Балыкчы', 15, 'Fisherman'),
  createWord('Мыловар', 'Самынчы', 15, 'Soap maker'),
  createWord('Плотник', 'Жыгач устасы', 15, 'Carpenter'),
  createWord('Певец, поэт', 'Ырчы', 15, 'Singer'),
  createWord('Историк', 'Тарыхчы', 15, 'Historian'),
  createWord('Лётчик', 'Учуучу', 15, 'Pilot'),
  // Одежда
  createWord('Одежда', 'Кийим', 16, 'Clothes'),
  createWord('Обувь', 'Бут кийим', 16, 'Shoes'),
  createWord('Рубашка', 'Көйнөк', 16, 'Shirt'),
  createWord('Шуба', 'Тон', 16, 'Fur coat'),
  createWord('Перчатки', 'Кол кап', 16, 'Gloves'),
  createWord('Штаны', 'Шым', 16, 'Pants'),
  createWord('Носки', 'Байпак', 16, 'Socks'),
  createWord('Платок', 'Жоолук', 16, 'Headscarf'),
  createWord('Часы', 'Саат', 16, 'Watch'),
  // Прилагательные
  createWord('Большой', 'Чоң', 17, 'Big'),
  createWord('Маленький', 'Кичине', 17, 'Small'),
  createWord('Умный', 'Акылдуу', 17, 'Smart'),
  createWord('Внутренний', 'Ички', 17, 'Internal'),
  createWord('Чистый', 'Таза', 17, 'Clean'),
  // Глаголы
  createWord('Входить', 'Кирүү', 18, 'Enter'),
  createWord('Выходить', 'Чыгуу', 18, 'Leave'),
  createWord('Играть', 'Ойноо', 18, 'Play'),
  createWord('Летать', 'Учуу', 18, 'Fly'),
  // Цветы
  createWord('Георгин', 'Георгин', 19, 'Dahlia'),
  createWord('Астра', 'Астра', 19, 'Aster'),
  createWord('Ромашка', 'Ромашка', 19, 'Chamomile'),
  // Насекомые
  createWord('Муравей', 'Кумурска', 20, 'Ant'),
  createWord('Бабочка', 'Көпөлөк', 20, 'Butterfly'),
  createWord('Таракан', 'Таракан', 20, 'Cockroach'),
  createWord('Оса', 'Аары', 20, 'Wasp'),
  createWord('Шмель', 'Аары', 20, 'Bumblebee'),
  createWord('Пчела', 'Бал аарысы', 20, 'Bee'),
  createWord('Муха', 'Чымын', 20, 'Fly')
]

export { TAGS, WORDS }