/**
 * Данные заполнители.
 *
 * @author Markitanov Vadim
 * @since 08.01.2025
 */
import { Tag } from '@/app/lib/model/entity/Tag'
import { WordEntity } from '@/app/lib/model/word'

/**
 * TODO:
 * Муха
 * Оранжевый
 */

const TAGS: Tag[] = [
  { id: 1, name: 'Разное' },
  { id: 2, name: 'Числительные', color: '#808080' },
  { id: 3, name: 'Цвета', color: '#F59E0B' },
  { id: 4, name: 'Фрукты', color: '#4CAF50' },
  { id: 5, name: 'Овощи', color: '#EF4444' },
  { id: 6, name: 'Дом', color: '#D8B384' },
  { id: 7, name: 'Животные', color: '#FB923C' },
  { id: 8, name: 'Дикие животные', color: '#D2B48C' },
  { id: 9, name: 'Строения', color: '#6B7280' },
  { id: 10, name: 'Природа', color: '#1E3A8A' },
  { id: 11, name: 'Еда и напитки', color: '#9A3412' },
  { id: 12, name: 'Человеческое тело', color: '#F5D7B6' },
  { id: 13, name: 'Материалы и вещества', color: '#2C3E50' },
  { id: 14, name: 'Птицы', color: '#87CEEB' },
  { id: 15, name: 'Город и село', color: '#8B4513' },
  { id: 16, name: 'Профессии', color: '#FFD700' },
  { id: 17, name: 'Одежда', color: '#FFC0CB' },
  { id: 18, name: 'Прилагательные', color: '#8A2BE2' },
  { id: 19, name: 'Глаголы', color: '#FF5733' },
  { id: 20, name: 'Цветы', color: '#FFB6C1' },
  { id: 21, name: 'Насекомые', color: '#FFD700' },
  { id: 22, name: 'Время', color: '#4682B4' }
]

const createWord = (ru: string, kg: string, tag: number, en: string): WordEntity => {
  return { id: 0, ru: ru, kg: kg, tag: tag, en: en }
}

const WORDS: WordEntity[] = [
  // Разное
  createWord('Работа', 'Иш, жумуш', 1, 'Job'),
  createWord('Игра', 'Оюн', 1, 'Game'),
  createWord('Начальник, сумка', 'Баштык', 1, 'Boss, bag'),
  createWord('Слово', 'Сөз', 1, 'Word'),
  createWord('Словарь', 'Сөздүк', 1, 'Dictionary'),
  createWord('Книга', 'Китеп', 1, 'Book'),
  createWord('Ребёнок', 'Бала', 1, 'Child'),
  createWord('Песня', 'Ыр', 1, 'Song'),
  createWord('Равно', 'Барабар', 1, 'Equals'),
  createWord('Больше', 'Чоң', 1, 'More'),
  createWord('Плюс', 'Кошуу белгиси', 1, 'Plus'),
  createWord('Умножение', 'Көбөйтүү', 1, 'Multiplication'),
  createWord('Деление', 'Бөлүү', 1, 'Division'),
  createWord('Знак, метка', 'Белги', 1, 'Sing, mark'),
  createWord('Деньги', 'Акча', 1, 'Money'),
  createWord('Лопата', 'Күрөк', 1, 'Shovel'),
  createWord('Хорошо', 'Жакшы', 1, 'Fine'),
  createWord('Плохо', 'Жаман', 1, 'Badly'),
  createWord('Полёт', 'Учуу', 1, 'Flight'),
  createWord('Да', 'Ооба', 1, 'Yes'),
  createWord('Нет', 'Жок', 1, 'No'),
  createWord('Или', 'Же', 1, 'Or'),
  createWord('И', 'Жана', 1, 'And'),
  createWord('Поиск', 'Издөө', 1, 'Search'),
  createWord('Промежуток', 'Ара', 1, 'Interval'),
  createWord('Копейка', 'Тыйын', 1, 'Kopeyka'),
  createWord('Колокол', 'Коңгуроо', 1, 'Bell'),
  createWord('Спасибо', 'Рахмат, ыракмат', 1, 'Thank you'),
  createWord('Он', 'Ал', 1, 'He'),
  createWord('Польза', 'Пайда', 1, 'Benefit'),
  createWord('Любовь', 'Сүйүү', 1, 'Love'),
  createWord('Лекарство', 'Дары', 1, 'Medicine'),
  createWord('Пена', 'Көбүк', 1, 'Foam'),
  createWord('Сон', 'Уйку', 1, 'Dream'),
  createWord('Мусор', 'Таштанды, Шыпырынды', 1, 'Garbage'),
  createWord('Тетрадь', 'Дептер', 1, 'Notebook'),
  // Числительные
  createWord('Ноль', 'Нөл', 2, 'Zero'),
  createWord('Один', 'Бир', 2, 'One'),
  createWord('Два', 'Эки', 2, 'Two'),
  createWord('Три', 'Үч', 2, 'Three'),
  createWord('Четыре', 'Төрт', 2, 'Four'),
  createWord('Пять', 'Беш', 2, 'Five'),
  createWord('Шесть', 'Алты', 2, 'Six'),
  createWord('Семь', 'Жети', 2, 'Seven'),
  createWord('Восемь', 'Сегиз', 2, 'Eight'),
  createWord('Девять', 'Тогуз', 2, 'Nine'),
  createWord('Десять', 'Он', 2, 'Ten'),
  createWord('Одиннадцать', 'Он бир', 2, 'Eleven'),
  createWord('Пятнадцать', 'Он беш', 2, 'Fifteen'),
  createWord('Шестнадцать', 'Он алты', 2, 'Sixteen'),
  createWord('Двадцать', 'Жыйырма', 2, 'Twenty'),
  createWord('Тридцать', 'Отуз', 2, 'Thirty'),
  createWord('Сорок', 'Кырк', 2, 'Forty'),
  createWord('Пятьдесят', 'Элүү', 2, 'Fifty'),
  createWord('Шестьдесят', 'Алтымыш', 2, 'Sixty'),
  createWord('Семьдесят', 'Жетимиш', 2, 'Seventy'),
  createWord('Восемьдесят', 'Сексен', 2, 'Eighty'),
  createWord('Девяносто', 'Токсон', 2, 'Ninety'),
  createWord('Тысяча', 'Миң', 2, 'Thousand'),
  // Цвета
  createWord('Белый', 'Ак', 3, 'White'),
  createWord('Черный', 'Кара', 3, 'Black'),
  createWord('Красный', 'Кызыл', 3, 'Red'),
  createWord('Зеленый', 'Жашыл', 3, 'Green'),
  createWord('Синий', 'Көк', 3, 'Blue'),
  createWord('Желтый', 'Сары', 3, 'Yellow'),
  createWord('Оранжевый', 'Кызгыл сары|Ачык күрөң', 3, 'Orange'),
  createWord('Фиолетовый', 'Кызгылт көк', 3, 'Purple'),
  createWord('Розовый', 'Кызыл, кызгылт', 3, 'Pink'),
  createWord('Коричневый', 'Күрөң', 3, 'Brown'),
  createWord('Серый', 'Боз, сур, көк', 3, 'Gray'),
  createWord('Голубой', 'Көк ачык', 3, 'Light Blue'),
  createWord('Бирюзовый', 'Бирюза түстүү', 3, 'Turquoise'),
  createWord('Лиловый', 'Кызгылт көгүш', 3, 'Lilac'),
  createWord('Песочный', 'Кум түстүү', 3, 'Sand'),
  createWord('Коралловый', 'Шуру (маржан) түстүү', 3, 'Coral'),
  createWord('Золотой', 'Алтын', 3, 'Gold'),
  createWord('Серебряный', 'Күмүш', 3, 'Silver'),
  createWord('Бронзовый', 'Коло түстүү', 3, 'Bronze'),
  // Фрукты
  createWord('Фрукт', 'Жемиш, мөмө', 4, 'Fruit'),
  createWord('Яблоко', 'Алма', 4, 'Apple'),
  createWord('Клубника', 'Кулпунай', 4, 'Strawberry'),
  createWord('Малина', 'Данкуурай', 4, 'Raspberry'),
  createWord('Груша', 'Алмурут', 4, 'Pear'),
  createWord('Виноград', 'Жүзүм', 4, 'Grape'),
  createWord('Арбуз', 'Дарбыз', 4, 'Water melon'),
  createWord('Дыня', 'Коон', 4, 'Melon'),
  createWord('Гранат', 'Анар', 4, 'Pomegranate'),
  createWord('Абрикос', 'Өрүк', 4, 'Apricot'),
  createWord('Слива', 'Кара өрүк', 4, 'Plum'),
  createWord('Персик', 'Шабдалы', 4, 'Peach'),
  createWord('Хурма', 'Курма', 4, 'Persimmon'),
  createWord('Смородина', 'Карагат', 4, 'Currant'),
  createWord('Ежевика', 'Бүлдүркөн', 4, 'Blackberry'),
  createWord('Облепиха', 'Чычырканак', 4, 'Guelder-rose'),
  createWord('Апельсин', 'Апельсин', 4, 'Orange'),
  createWord('Вишня', 'Чие', 4, 'Cherry'),
  // Овощи
  createWord('Овощи', 'Жашылчалар', 5, 'Vegetables'),
  createWord('Картофель', 'Картөшкө', 5, 'Potato'),
  createWord('Морковь', 'Сабиз', 5, 'Carrot'),
  createWord('Лук', 'Пияз', 5, 'Onion'),
  createWord('Чеснок', 'Сарымсак', 5, 'Garlic'),
  createWord('Горох', 'Буурчак', 5, 'Peas'),
  createWord('Огурец', 'Бадыраң', 5, 'Cucumber'),
  createWord('Капуста', 'Капуста', 5, 'Cabbage'),
  createWord('Кукуруза', 'Жүгөрү', 5, 'Corn'),
  createWord('Помидор', 'Помидор', 5, 'Tomato'),
  createWord('Тыква', 'Ашкабак', 5, 'Pumpkin'),
  createWord('Салат', 'Салат', 5, 'Lettuce'),
  createWord('Репа', 'Шалгам', 5, 'Turnip'),
  createWord('Редис', 'Чамгыр', 5, 'Radish'),
  createWord('Редька', 'Редька', 5, 'Summer radish'),
  createWord('Баклажан', 'Баклажан', 5, 'Eggplant'),
  createWord('Укроп', 'Ашкөк', 5, 'Dill'),
  createWord('Свекла', 'Кызылча', 5, 'Beetroot'),
  createWord('Кабачок', 'Кабачок', 5, 'Vegetable marrow'),
  createWord('Щавель', 'Ат кулак', 5, 'Sorrel'),
  // Дом
  createWord('Дом', 'Үй', 6, 'House'),
  createWord('Этаж', 'Кабат', 6, 'Floor'),
  createWord('Квартира', 'Батир', 6, 'Apartment'),
  createWord('Дверь', 'Эшик', 6, 'Door'),
  createWord('Окно', 'Терезе', 6, 'Window'),
  createWord('Ложка', 'Кашык', 6, 'Spoon'),
  createWord('Вилка', 'Вилка', 6, 'Fork'),
  createWord('Нож', 'Бычак', 6, 'Knife'),
  createWord('Ключ', 'Ачкыч', 6, 'Key'),
  createWord('Подушка', 'Жаздык', 6, 'Pillow'),
  createWord('Мыло', 'Самын', 6, 'Soap'),
  createWord('Стакан', 'Стакан', 6, 'Cup'),
  createWord('Зеркало', 'Күзгү', 6, 'Mirror'),
  createWord('Тарелка', 'Табак', 6, 'Plate'),
  // Животные
  createWord('Животное', 'Айбан', 7, 'Animal'),
  createWord('Кошка', 'Мышык', 7, 'Cat'),
  createWord('Собака', 'Ит', 7, 'Dog'),
  createWord('Корова', 'Уй', 7, 'Cow'),
  createWord('Осёл', 'Эшек', 7, 'Donkey'),
  createWord('Овца', 'Кой', 7, 'Sheep'),
  createWord('Свинья', 'Чочко', 7, 'Pig'),
  createWord('Поросёнок', 'Торпой', 7, 'Piglet'),
  createWord('Верблюд', 'Төө', 7, 'Camel'),
  createWord('Лягушка', 'Бака', 7, 'Frog'),
  createWord('Бык', 'Бука', 7, 'Bull'),
  createWord('Черепаха', 'Ташбака', 7, 'Turtle'),
  createWord('Кролик', 'Кролик', 7, 'Rabbit'),
  createWord('Лошадь', 'Жылкы', 7, 'Horse'),
  createWord('Жеребёнок', 'Кулун', 7, 'Foal'),
  createWord('Ягнёнок', 'Козу', 7, 'Lamb'),
  createWord('Телёнок', 'Музоо', 7, 'Calf'),
  createWord('Котёнок', 'Мышыктын баласы', 7, 'Kitten'),
  createWord('Щенок', 'Күчүк', 7, 'Puppy'),
  // Дикие животные
  createWord('Олень', 'Бугу', 8, 'Deer'),
  createWord('Лось', 'Багыш', 8, 'Elk'),
  createWord('Медведь', 'Аюу', 8, 'Bear'),
  createWord('Слон', 'Пил', 8, 'Elephant'),
  createWord('Лев', 'Арстан', 8, 'Lion'),
  createWord('Волк', 'Карышкыр', 8, 'Wolf'),
  createWord('Барс', 'Илбирс', 8, 'Leopard'),
  createWord('Кабан', 'Каман', 8, 'Boar'),
  createWord('Тигр', 'Жолборс', 8, 'Tiger'),
  createWord('Зебра', 'Зебра', 8, 'Zebra'),
  createWord('Жираф', 'Жираф', 8, 'Giraffe'),
  createWord('Носорог', 'Керик', 8, 'Rhinoceros'),
  createWord('Заяц', 'Коён', 8, 'Hare'),
  createWord('Белка', 'Тыйын чычкан', 8, 'Squirrel'),
  createWord('Мышь', 'Чычкан', 8, 'Squirrel'),
  createWord('Ёж', 'Кирпи', 8, 'Hedgehog'),
  createWord('Лиса', 'Түлкү', 8, 'Fox'),
  createWord('Енот', 'Енот', 8, 'Raccoon'),
  createWord('Обезьяна', 'Маймыл', 8, 'Monkey'),
  createWord('Змея', 'Жылан', 8, 'Snake'),
  // Строения
  createWord('Магазин', 'Дүкөн', 9, 'Shop'),
  createWord('Аптека', 'Дарыкана', 9, 'Pharmacy'),
  createWord('Школа', 'Мектеп', 9, 'School'),
  createWord('Столовая', 'Ашкана', 9, 'Dining room'),
  createWord('Больница', 'Оорукана', 9, 'Hospital'),
  createWord('Гостиница', 'Мейманкана', 9, 'Hotel'),
  createWord('Библиотека', 'Китепкана', 9, 'Library'),
  createWord('Парикмахерская', 'Чачтарач', 9, 'Salon'),
  createWord('Типография', 'Басманкана', 9, 'Printing house'),
  createWord('Туалет', 'Даараткана', 9, 'Toilet'),
  createWord('Туалет', 'Ажаткана', 9, 'Toilet'),
  // Природа
  createWord('Море', 'Деңиз', 10, 'Sea'),
  createWord('Гора', 'Тоо', 10, 'Mountain'),
  createWord('Лес', 'Токой', 10, 'Forest'),
  createWord('Луна', 'Ай', 10, 'Moon'),
  createWord('Озеро', 'Көл', 10, 'Lake'),
  createWord('Дерево', 'Жыгач', 10, 'Tree'),
  createWord('Камень', 'Таш', 10, 'Stone'),
  createWord('Снег', 'Кар', 10, 'Snow'),
  createWord('Поле', 'Талла', 10, 'Field'),
  createWord('Пруд', 'Көлмө', 10, 'Pond'),
  createWord('Река', 'Дарыя', 10, 'River'),
  createWord('Зима', 'Кыш', 10, 'Winter'),
  createWord('Весна', 'Жаз', 10, 'Spring'),
  createWord('Лето', 'Жай', 10, 'Summer'),
  createWord('Осень', 'Күз', 10, 'Autumn'),
  createWord('Небо', 'Асман', 10, 'Sky'),
  createWord('Долина', 'Өрөөн', 10, 'Valley'),
  // Еда и напитки
  createWord('Еда', 'Тамак', 11, 'Food'),
  createWord('Пища', 'Аш', 11, 'Food'),
  createWord('Вода', 'Суу', 11, 'Water'),
  createWord('Молоко', 'Сүт', 11, 'Milk'),
  createWord('Пиво', 'Сыра', 11, 'Beer'),
  createWord('Водка', 'Арак', 11, 'Vodka'),
  createWord('Мясо', 'Эт', 11, 'Meat'),
  createWord('Хлеб', 'Нан', 11, 'Bread'),
  createWord('Соль', 'Туз', 11, 'Salt'),
  createWord('Гриб', 'Козу карын', 11, 'Mushroom'),
  createWord('Яд', 'Уу', 11, 'Poison'),
  createWord('Мёд', 'Бал', 11, 'Honey'),
  createWord('Суп', 'Сорпо', 11, 'Soup'),
  createWord('Состав', 'Курама', 11, 'Compound'),
  createWord('Бутылка', 'Бөтөлкө', 11, 'Bottle'),
  // Человеческое тело
  createWord('Человек', 'Адам', 12, 'Human'),
  createWord('Голова', 'Баш', 12, 'Head'),
  createWord('Ухо', 'Кулак', 12, 'Ear'),
  createWord('Губа', 'Эрин', 12, 'Lip'),
  createWord('Рот', 'Ооз', 12, 'Mouth'),
  createWord('Глаз', 'Көз', 12, 'Eye'),
  createWord('Нос', 'Мурун', 12, 'Nose'),
  createWord('Палец', 'Бармак', 12, 'Finger'),
  createWord('Рука', 'Кол', 12, 'Hand'),
  createWord('Волос', 'Чач', 12, 'Hair'),
  createWord('Кровь', 'Кан', 12, 'Blood'),
  createWord('Зуб', 'Тиш', 12, 'Tooth'),
  createWord('Нога', 'Бут', 12, 'Leg'),
  createWord('Внутренность', 'Ич', 12, 'Interior'),
  createWord('Борода', 'Сакал', 12, 'Beard'),
  // Материалы и вещества
  createWord('Материал', 'Материал', 13, 'Material'),
  createWord('Вещество', 'Зат', 13, 'Substance'),
  createWord('Золото', 'Алтын', 13, 'Gold'),
  createWord('Серебро', 'Күмүш', 13, 'Silver'),
  createWord('Уголь', 'Көмүр', 13, 'Coal'),
  createWord('Железо', 'Темир', 13, 'Iron'),
  createWord('Песок', 'Кум', 13, 'Sand'),
  createWord('Древесина', 'Жыгач', 13, 'Wood'),
  createWord('Бумага', 'Кагаз', 13, 'Paper'),
  createWord('Стекло', 'Айнек', 13, 'Glass'),
  createWord('Табак', 'Тамеки', 13, 'Tobacco'),
  createWord('Кирпич', 'Кыш', 13, 'Brick'),
  // Птицы
  createWord('Птицы', 'Куштар', 14, 'Birds'),
  createWord('Курица', 'Тоок', 14, 'Hen'),
  createWord('Петух', 'Короз', 14, 'Cock'),
  createWord('Гусь', 'Каз', 14, 'Goose'),
  createWord('Утка', 'Өрдөк', 14, 'Duck'),
  createWord('Голубь', 'Көгүчкөн', 14, 'Pigeon'),
  createWord('Попугай', 'Тоту куш', 14, 'Parrot'),
  createWord('Ворона', 'Карга', 14, 'Crow'),
  createWord('Воробей', 'Чыьчык', 14, 'Sparrow'),
  createWord('Орёл', 'Бүркүт', 14, 'Eagle'),
  createWord('Аист', 'Илегилек', 14, 'Stork'),
  createWord('Лебедь', 'Ак куу', 14, 'Swan'),
  createWord('Дятел', 'Тоңкулдак', 14, 'Woodpecker'),
  createWord('Сова', 'Үкү', 14, 'Owl'),
  createWord('Фазан', 'Кыргоол', 14, 'Peacock'),
  createWord('Куропатка', 'Чил', 14, 'Partridge'),
  createWord('Синица', 'Синица', 14, 'Blue-tit'),
  createWord('Индюк', 'Күрп, үндүк', 14, 'Turkey'),
  createWord('Снегирь', 'Снегирь', 14, 'Bullfinch'),
  createWord('Кукушка', 'Күкүк', 14, 'Cuckoo'),
  createWord('Сорока', 'Сагызган', 14, 'Magpie'),
  createWord('Гусёнок', 'Каздын балапаны', 14, 'Gosling'),
  createWord('Утёнок', 'Өрдөктүн балапаны', 14, 'Duckling'),
  createWord('Цыплёнок', 'Жөжө', 14, 'Chicken'),
  // Город и село
  createWord('Город', 'Шаар', 15, 'City'),
  createWord('Флаг', 'Желек', 15, 'Flag'),
  createWord('Село, деревня', 'Айыл', 15, 'Village'),
  createWord('Улица', 'Көчө', 15, 'Street'),
  createWord('Площадь', 'Аянт', 15, 'Square'),
  createWord('Мост', 'Көпүрө', 15, 'Bridge'),
  createWord('Торговый центр', 'Соода борбору', 15, 'Shopping mall'),
  createWord('Дорога', 'Жол', 15, 'Road'),
  createWord('Уличный фонарь', 'Панар', 15, 'Street lamp'),
  createWord('Мечеть', 'Мечит', 15, 'Mosque'),
  createWord('Рынок', 'Базар', 15, 'Market'),
  createWord('Ж/д вокзал', 'Темир жол вокзалы', 15, 'Railway station'),
  // Профессии
  createWord('Мастер', 'Уста', 16, 'Master'),
  createWord('Строитель', 'Куруучу', 16, 'Builder'),
  createWord('Учитель', 'Мугалим', 16, 'Teacher'),
  createWord('Преподаватель', 'Окутуучу', 16, 'Teacher'),
  createWord('Рыбак', 'Балыкчы', 16, 'Fisherman'),
  createWord('Мыловар', 'Самынчы', 16, 'Soap maker'),
  createWord('Плотник', 'Жыгач устасы', 16, 'Carpenter'),
  createWord('Певец, поэт', 'Ырчы', 16, 'Singer'),
  createWord('Историк', 'Тарыхчы', 16, 'Historian'),
  createWord('Лётчик', 'Учуучу', 16, 'Pilot'),
  createWord('Стекловар', 'Айнек кайнатуучу', 16, 'Glassmaker'),
  // Одежда
  createWord('Одежда', 'Кийим', 17, 'Clothes'),
  createWord('Обувь', 'Бут кийим', 17, 'Shoes'),
  createWord('Рубашка', 'Көйнөк', 17, 'Shirt'),
  createWord('Шуба', 'Тон', 17, 'Fur coat'),
  createWord('Перчатки', 'Кол кап', 17, 'Gloves'),
  createWord('Штаны', 'Шым', 17, 'Pants'),
  createWord('Носки', 'Байпак', 17, 'Socks'),
  createWord('Платок', 'Жоолук', 17, 'Headscarf'),
  createWord('Часы', 'Саат', 17, 'Watch'),
  // Прилагательные
  createWord('Большой', 'Чоң', 18, 'Big'),
  createWord('Маленький', 'Кичине', 18, 'Small'),
  createWord('Умный', 'Акылдуу', 18, 'Smart'),
  createWord('Внутренний', 'Ички', 18, 'Internal'),
  createWord('Чистый', 'Таза', 18, 'Clean'),
  createWord('Сладкий', 'Таттуу', 18, 'Sweet'),
  createWord('Горький', 'Ачуу', 18, 'Bitter'),
  createWord('Вкусный', 'Даамдуу', 18, 'Delicious'),
  createWord('Кислый', 'Кычкыл', 18, 'Sour'),
  createWord('Острый', 'Өткүр', 18, 'Spicy'),
  createWord('Новый', 'Жаңы', 18, 'New'),
  createWord('Хитрый (лукавый)', 'Куу', 18, 'Cunning'),
  createWord('Густой, частый', 'Калың', 18, 'Thick, frequent'),
  createWord('Губастый', 'Калың эриндүү', 18, 'Thick-lipped'),
  // Глаголы
  createWord('Входить', 'Кирүү', 19, 'Enter'),
  createWord('Выходить', 'Чыгуу', 19, 'Leave'),
  createWord('Играть', 'Ойноо', 19, 'Play'),
  createWord('Летать', 'Учуу', 19, 'Fly'),
  createWord('Учиться', 'Окуу', 19, 'Study'),
  createWord('Быть, становится', 'Бол', 19, 'Be'),
  createWord('Кипятить', 'Кайнатуу', 19, 'Boil'),
  // Цветы
  createWord('Цветы', 'Гүлдөр', 20, 'Flowers'),
  createWord('Георгин', 'Георгин', 20, 'Dahlia'),
  createWord('Астра', 'Астра', 20, 'Aster'),
  createWord('Ромашка', 'Ромашка', 20, 'Chamomile'),
  createWord('Тюльпан', 'Жоогазын', 20, 'Tulip'),
  createWord('Голубой колокольчик', 'Көк коңгуроо', 20, 'Blue bell'),
  createWord('Лилия', 'Лилия', 20, 'Lily'),
  createWord('Пион', 'Пион', 20, 'Peony'),
  createWord('Василёк', 'Кекире', 20, 'Corn-flower'),
  createWord('Орхидея', 'Орхидея', 20, 'Orchid'),
  createWord('Ландыш', 'Ландыш', 20, 'Lily valley'),
  createWord('Нарцисс', 'Нарцисс', 20, 'Narcissus'),
  // Насекомые
  createWord('Муравей', 'Кумурска', 21, 'Ant'),
  createWord('Бабочка', 'Көпөлөк', 21, 'Butterfly'),
  createWord('Таракан', 'Таракан', 21, 'Cockroach'),
  createWord('Оса', 'Аары', 21, 'Wasp'),
  createWord('Шмель', 'Аары', 21, 'Bumblebee'),
  createWord('Пчела', 'Бал аарысы', 21, 'Bee'),
  createWord('Муха', 'Чымын', 21, 'Fly'),
  // Время
  createWord('Время', 'Убакыт', 22, 'Time'),
  createWord('Секунда', 'Секунда', 22, 'Second'),
  createWord('Минута', 'Минута', 22, 'Minute'),
  createWord('Час', 'Саат', 22, 'Hour'),
  createWord('Месяц', 'Ай', 22, 'Month'),
  createWord('Год', 'Жыл', 22, 'Year'),
  createWord('Пятница', 'Жума', 22, 'Friday'),
]

export { TAGS, WORDS }