/**
 * Данные заполнители.
 *
 * @author Markitanov Vadim
 * @since 08.01.2025
 */
import { Tag } from '@/app/lib/model/entity/Tag'
import { WordEntity } from '@/app/lib/model/word'

const TAGS: Tag[] = [
  { id: 1, name: 'Разное' },
  { id: 2, name: 'Числительные', color: '#808080' },
  { id: 3, name: 'Цвета', color: '#F59E0B' },
  { id: 4, name: 'Фрукты', color: '#4CAF50' },
  { id: 5, name: 'Овощи', color: '#EF4444' },
  { id: 6, name: 'Дом', color: '#D8B384' },
  { id: 7, name: 'Животные', color: '#FB923C' },
  { id: 8, name: 'Строения', color: '#6B7280' },
  { id: 9, name: 'Природа', color: '#1E3A8A' },
  { id: 10, name: 'Еда и напитки', color: '#9A3412' },
  { id: 11, name: 'Человеческое тело', color: '#F5D7B6' },
  { id: 12, name: 'Материал', color: '#2C3E50' },
  { id: 13, name: 'Птицы', color: '#87CEEB' },
  { id: 14, name: 'Город и село', color: '#8B4513' },
  { id: 15, name: 'Профессии', color: '#FFD700' },
  { id: 16, name: 'Одежда', color: '#FFC0CB' }
]

const createWord = (ru: string, kg: string, tag: number, en?: string): WordEntity => {
  return { id: 0, ru: ru, kg: kg, tag: tag, en: en }
}

const WORDS: WordEntity[] = [
  // Разное
  createWord('Большой', 'Чоң', 1, 'Big'),
  createWord('Маленький', 'Кичине', 1, 'Small'),
  createWord('Работа', 'Иш, жумуш', 1),
  createWord('Внутренний', 'Ички', 1),
  createWord('Входить', 'Кирүү', 1),
  createWord('Выходить', 'Чыгуу', 1),
  createWord('Играть', 'Ойноо', 1),
  createWord('Игра', 'Оюн', 1),
  createWord('Начальник, Сумка', 'Баштык', 1),
  createWord('Слово', 'Сөз', 1),
  createWord('Словарь', 'Сөздүк', 1),
  createWord('Книга', 'Китеп', 1),
  createWord('Ребёнок', 'Бала', 1),
  createWord('Песня', 'Ыр', 1),
  // Числительные
  createWord('Ноль', 'Нөл', 2),
  createWord('Один', 'Бир', 2),
  createWord('Два', 'Эки', 2),
  createWord('Три', 'Үч', 2),
  createWord('Четыре', 'Төрт', 2),
  createWord('Пять', 'Беш', 2),
  createWord('Шесть', 'Алты', 2),
  createWord('Семь', 'Жети', 2),
  createWord('Восемь', 'Сегиз', 2),
  createWord('Девять', 'Тогуз', 2),
  createWord('Десять', 'Он', 2),
  createWord('Двадцать', 'Жыйырма', 2),
  createWord('Тридцать', 'Отуз', 2),
  createWord('Сорок', 'Кырк', 2),
  createWord('Пятьдесят', 'Элүү', 2),
  createWord('Шестьдесят', 'Алтымыш', 2),
  createWord('Семьдесят', 'Жетимиш', 2),
  createWord('Восемьдесят', 'Сексен', 2),
  createWord('Девяносто', 'Токсон', 2),
  createWord('Тысяча', 'Миң', 2),
  // Цвета
  { id: 0, ru: 'Белый', kg: 'Ак', tag: 3 },
  { id: 0, ru: 'Черный', kg: 'Кара', tag: 3 },
  { id: 0, ru: 'Красный', kg: 'Кызыл', tag: 3 },
  { id: 0, ru: 'Зеленый', kg: 'Жашыл', tag: 3 },
  { id: 0, ru: 'Синий', kg: 'Көк', tag: 3 },
  { id: 0, ru: 'Желтый', kg: 'Сары', tag: 3 },
  { id: 0, ru: 'Оранжевый', kg: 'Кызгыл сары|Ачык күрөң', tag: 3 },
  { id: 0, ru: 'Фиолетовый', kg: 'Кызгылт көк', tag: 3 },
  { id: 0, ru: 'Розовый', kg: 'Кызыл, кызгылт', tag: 3 },
  { id: 0, ru: 'Коричневый', kg: 'Күрөң', tag: 3 },
  { id: 0, ru: 'Серый', kg: 'Боз, сур, көк', tag: 3 },
  { id: 0, ru: 'Голубой', kg: 'Көк', tag: 3 },
  { id: 0, ru: 'Бирюзовый', kg: 'Бирюза түстүү', tag: 3 },
  { id: 0, ru: 'Лиловый', kg: 'Кызгылт көгүш', tag: 3 },
  { id: 0, ru: 'Песочный', kg: 'Кум түстүү', tag: 3 },
  { id: 0, ru: 'Коралловый', kg: 'Шуру (маржан) түстүү', tag: 3 },
  { id: 0, ru: 'Золотой', kg: 'Алтын', tag: 3 },
  { id: 0, ru: 'Серебряный', kg: 'Күмүш', tag: 3 },
  { id: 0, ru: 'Бронзовый', kg: 'Коло түстүү', tag: 3 },
  // Фрукты
  createWord('Яблоко', 'Алма', 4),
  { id: 0, ru: 'Груша', kg: 'Алмурут', tag: 4 },
  { id: 0, ru: 'Виноград', kg: 'Жүзүм', tag: 4 },
  { id: 0, ru: 'Арбуз', kg: 'Дарбыз', tag: 4 },
  { id: 0, ru: 'Дыня', kg: 'Коон', tag: 4 },
  { id: 0, ru: 'Гранат', kg: 'Анар', tag: 4 },
  { id: 0, ru: 'Абрикос', kg: 'Өрүк', tag: 4 },
  { id: 0, ru: 'Персик', kg: 'Шабдалы', tag: 4 },
  createWord('Хурма', 'Курма', 4),
  // Овощи
  createWord('Картофель', 'Картөшкө', 5),
  createWord('Морковь', 'Сабиз', 5),
  createWord('Лук', 'Пияз', 5),
  createWord('Чеснок', 'Сарымсак', 5),
  createWord('Горох', 'Буурчак', 5),
  createWord('Огурец', 'Бадыраң', 5),
  // Дом
  createWord('Дом', 'Үй', 6),
  createWord('Этаж', 'Кабат', 6),
  createWord('Дверь', 'Эшик', 6),
  createWord('Окно', 'Терезе', 6),
  createWord('Ложка', 'Кашык', 6),
  createWord('Нож', 'Бычак', 6),
  createWord('Ключ', 'Ачкыч', 6),
  createWord('Подушка', 'Жаздык', 6),
  createWord('Мыло', 'Самын', 6),
  // Животные
  createWord('Кошка', 'Мышык', 7),
  createWord('Собака', 'Ит', 7),
  createWord('Корова', 'Уй', 7),
  createWord('Медведь', 'Аюу', 7),
  createWord('Осёл', 'Эшек', 7),
  createWord('Олень', 'Бугу', 7),
  createWord('Свинья', 'Чочко', 7),
  createWord('Поросёнок', 'Торпой', 7),
  createWord('Слон', 'Пил', 7),
  createWord('Лев', 'Арстан', 7),
  createWord('Тигр', 'Жолборс', 7),
  createWord('Верблюд', 'Төө', 7),
  createWord('Лягушка', 'Бака', 7),
  createWord('Бука', 'Бык', 7),
  createWord('Черепаха', 'Ташбака', 7),
  // Строения
  createWord('Магазин', 'Дүкөн', 8),
  createWord('Аптека', 'Дарыкана', 8),
  createWord('Школа', 'Мектеп', 8),
  createWord('Больница', 'Оорукана', 8),
  createWord('Гостиница', 'Мейманкана', 8),
  createWord('Библиотека', 'Китепкана', 8),
  createWord('Парикмахерская', 'Чачтарач', 8),
  createWord('Типография', 'Басманкана', 8),
  createWord('Стоматология', 'Тишкана', 8),
  // Природа
  createWord('Море', 'Деңиз', 9),
  createWord('Гора', 'Тоо', 9),
  createWord('Лес', 'Токой', 9),
  createWord('Озеро', 'Көл', 9),
  createWord('Дерево', 'Жыгач', 9),
  createWord('Камень', 'Таш', 9),
  createWord('Снег', 'Кар', 9),
  createWord('Поле', 'Талла', 9),
  createWord('Пруд', 'Көлмө', 9),
  createWord('Река', 'Дарыя', 9),
  // Еда и напитки
  createWord('Еда', 'Тамак', 10),
  createWord('Вода', 'Суу', 10),
  createWord('Молоко', 'Сүт', 10),
  createWord('Пиво', 'Сыра', 10),
  createWord('Водка', 'Арак', 10),
  createWord('Мясо', 'Эт', 10),
  createWord('Хлеб', 'Нан', 10),
  createWord('Соль', 'Туз', 10),
  createWord('Кукуруза', 'Жүгөрү', 10),
  createWord('Гриб', 'Козу карын', 10),
  createWord('Яд', 'Уу', 10),
  // Человеческое тело
  createWord('Человек', 'Адам', 11),
  createWord('Голова', 'Баш', 11),
  createWord('Глаз', 'Көз', 11),
  createWord('Нос', 'Мурун', 11),
  createWord('Палец', 'Бармак', 11),
  createWord('Рука', 'Кол', 11),
  createWord('Волос', 'Чач', 11),
  createWord('Кровь', 'Кан', 11),
  createWord('Зуб', 'Тиш', 11),
  createWord('Нога', 'Бут', 11),
  createWord('Внутренность', 'Ич', 11),
  // Материал
  createWord('Золото', 'Алтын', 12),
  createWord('Серебро', 'Күмүш', 12),
  createWord('Уголь', 'Көмүр', 12),
  createWord('Железо', 'Темир', 12),
  createWord('Песок', 'Кум', 12),
  createWord('Древесина', 'Жыгач', 12),
  // Птицы
  createWord('Птица', 'Куш', 13),
  createWord('Курица', 'Тоок', 13),
  createWord('Голубь', 'Көгүчкөн', 13),
  createWord('Ворона', 'Карга', 13),
  createWord('Орёл', 'Бүркүт', 13),
  createWord('Сова', 'Үкү', 13),
  createWord('Фазан', 'Кыргоол', 13),
  // Город и село
  createWord('Город', 'Шаар', 14),
  createWord('Село, деревня', 'Айыл', 14),
  createWord('Улица', 'Көчө', 14),
  createWord('Площадь', 'Аянт', 14),
  createWord('Мост', 'Көпүрө', 14),
  createWord('Торговый центр', 'Соода борбору', 14),
  createWord('Дорога', 'Жол', 14),
  createWord('Фонарь', 'Панар', 14),
  createWord('Мечеть', 'Мечит', 14),
  createWord('Рынок', 'Базар', 14),
  createWord('Ж/д вокзал', 'Темир жол вокзалы', 14),
  // Профессии
  createWord('Мастер', 'Уста', 15),
  createWord('Строитель', 'Куруучу', 15),
  createWord('Учитель', 'Мугалим', 15),
  createWord('Преподаватель', 'Окутуучу', 15),
  createWord('Рыбак', 'Балыкчы', 15),
  createWord('Мыловар', 'Самынчы', 15),
  createWord('Плотник', 'Жыгач устасы', 15),
  createWord('Певец, поэт', 'Ырчы', 15),
  // Одежда
  createWord('Одежда', 'Кийим', 16),
  createWord('Обувь', 'Бут кийим', 16),
  createWord('Рубашка', 'Көйнөк', 16),
  createWord('Шуба', 'Тон', 16)
]

export { TAGS, WORDS }